### ISSUE TITLE
Question about dcfinder - "MinimalCoverCandidate.java"

### ISSUE THREAD

**Issue by yyssl88** [HPI-Information-Systems/metanome-algorithms#12]
In MinimalCoverCandidate.java, the following function is to generate filtered EvidenceSet:

	private IEvidenceSet getFilteredEvidenceSet(Predicate add, Collection<Predicate> addablePredicates) {
		IEvidenceSet filteredEvidence = new TroveEvidenceSet();
		IBitSet addables = PredicateSetFactory.create(addablePredicates).getBitset();
		Iterator<PredicateSet> iter = evidenceSet.iterator();
		int addIndex = PredicateSet.getIndex(add);
		while (iter.hasNext()) {
			PredicateSet pSet = iter.next();
			IBitSet bs = pSet.getBitset();
			if (bs.get(addIndex)) {

				if (addables.isSubSetOf(bs)) {
					return null;
				}

				bs = bs.clone();
				bs.and(addables);
	
				filteredEvidence.add(PredicateSetFactory.create(bs), evidenceSet.getCount(pSet));
			}
		}
		return filteredEvidence;
	}

In lin 151 "if (bs.get(addIndex)) {" in the .java file, the code aims to find all evidences that contain predicate "add". However, I think the minimal cover algorithm should filter evidences that contain "add". 

Do I miss something? 
Thanks, and look forward to your reply.

**Comment by eduardohmpena** [comment]
The cover search finds anti-covers of the EvidenceSet. An anti-cover contains at least one predicate for every element of the EvidenseSet, which is not present in that element. By finding anti-covers we don`t need to invert covers at the end of the search, that is why the filtering is based on pieces of evidence that contain predicate  "add".

**Comment by yaoshuwang** [comment]
I got it, thanks !
