### ISSUE TITLE
HYFD

### ISSUE THREAD

**Issue by amin9565** [HPI-Information-Systems/metanome-algorithms#13]
hello 
i have a problem with HYFD
when i write mvn install after 2 seconds it shown:
Could not resolve dependencies for project de.metanome.algorithms.hyfd:HyFD:jar:1.2-SNAPSHOT ...
what do i do ?
thank you in advanced

**Comment by thorsten-papenbrock** [comment]
Dear Amin,
could you describe your issue in a bit more detail so we can actually understand what is going on? After cloning the repository, what are your exact commands that lead to this error? Have you built Metanome before? In which folder do you run which commands? What is the entire log output around this error message (please post like the 20 lines before and everything after it)? What is your environment, i.e., OS, Java version etc.?
Best,
Thorsten

**Comment by amin9565** [comment]
in first i downloaded repository and i open HYFD folder and run cmd and then type mvn install
then it shown this error.

`PS D:\Dl\metanome-algorithms-master\metanome-algorithms-master\HyFD> mvn install                                        [INFO] Scanning for projects...
[INFO]
[INFO] ------------------< de.metanome.algorithms.hyfd:HyFD >------------------
[INFO] Building HyFD 1.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for de.uni-potsdam.hpi:utils:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.uni-potsdam.hpi:dao:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.metanome:algorithm_integration:jar:1.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.metanome:backend:jar:1.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.559 s
[INFO] Finished at: 2020-02-04
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project HyFD: Could not resolve dependencies for project de.metanome.algorithms.hyfd:HyFD:jar:1.2-SNAPSHOT: The following artifacts could not be resolved: de.uni-potsdam.hpi:utils:jar:0.0.1-SNAPSHOT, de.uni-potsdam.hpi:dao:jar:0.0.1-SNAPSHOT, de.metanome:algorithm_integration:jar:1.2-SNAPSHOT, de.metanome:backend:jar:1.2-SNAPSHOT: Could not find artifact de.uni-potsdam.hpi:utils:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by thorsten-papenbrock** [comment]
Ah good, then it's a simple issue: You have to run the "mvn install" in the parent folder, i.e., in the folder:
`D:\Dl\metanome-algorithms-master\metanome-algorithms-master`
It will then compile all algorithm including HyFD and its dependencies.

**Comment by amin9565** [comment]
thank you for answer 
new error is :
` BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.574 s
[INFO] Finished at: 2020-02-04
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project utils: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]`

**Comment by thorsten-papenbrock** [comment]
And do you have a JRE installed instead of a JDK as the error message says?

**Comment by amin9565** [comment]
i have JRE and JDK and i don't any change in the project.

**Comment by thorsten-papenbrock** [comment]
The error you see has nothing to do with our project but with the development setup of your machine. If you installed the JDK, the JAVA_HOME is probably not set correctly on your machine's PATH? That could be why the build command cannot find it.

**Comment by amin9565** [comment]
sorry for very problems...
new error is :

` BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.313 s
[INFO] Finished at: 2020-02-05
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project BINDERAlgorithm: Could not resolve dependencies for project de.metanome.algorithms.binder:BINDERAlgorithm:jar:1.2-SNAPSHOT: Could not find artifact de.metanome:algorithm_integration:jar:1.2-SNAPSHOT `

**Comment by thorsten-papenbrock** [comment]
This is because you did not follow the build instructions: You need to build the Metanome tool first, because the algorithms need some libraries from that project.

So checkout this repository: https://github.com/HPI-Information-Systems/Metanome

Then run 
`git submodule init`
`git submodule update`
`mvn install`

That will build the missing dependencies (inter alia de.metanome:algorithm_integration:jar:1.2-SNAPSHOT) and put them into your local maven repository so that the algorithm build process will find them.

**Comment by amin9565** [comment]
thank you i build it finally.
in first download the project with `git clone https://github.com/HPI-Information-Systems/metanome-algorithms.git`
and then i run 3 lines that you say in above.
now i want built one of algorithm but i don't understand this sentence in tutorial 
> specify -Xmx1g -Xms20m -Xss10m as build parameters.

i open one of the algorithm in intellij IDEA and what do i do ?

**Comment by thorsten-papenbrock** [comment]
The easiest way of building Metanome is by simply installing maven and java on your computer and then running the commands on the console in the Metanome folder. 

In intellij IDEA, you first import Metanome as a maven project (I guess that is as far as you got). Then, you should see "Maven Projects" on the very right of your window. Click it and then the small icon "Maven Settings". Go to "Build, Execution, Deployment" -> "Build Tools" -> "Maven" -> "Runners" and specify the build parameters in the field for "VM Options". Then say "OK" and run the install Lifecycle goal.

**Comment by amin9565** [comment]
![image](https://user-images.githubusercontent.com/23387182/74222614-279e1e00-4cca-11ea-93e6-4b3ce5da6125.png)

this error is :
 No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.

**Comment by amin9565** [comment]
can you help me ?

**Comment by thorsten-papenbrock** [comment]
That is because you tried to compile only the HyFD algorithm. You need to compile all algorithms, because every algorithm in that repository is only a submodule of the entire algorithms project. Try not to run the Lifecycle arguments on the individual submodules but on the entire metanome-algorithms project. You should find that project if you scroll down a bit in the list of Maven projects in the window on the right.

**Comment by amin9565** [comment]
thank you but how to compile all algorithm ?

**Comment by thorsten-papenbrock** [comment]
What I wrote did not work? Find the metanome-algorithms project in the Maven tab on the right and then run the package Lifecycle on that project. It is the project/folder, in which all the algorithms are placed. Intellij should list that project for your. If you package that project, it will package all algorithms in it.
