### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by faisal-ksolves** [HPI-Information-Systems/metanome-algorithms#68]
hello everyone,
I am looking for a proper documentation which describe working of each algorithms of metanome.
can anyone help to find doc.

Thanks in advance :)

**Comment by sekruse** [comment]
Most algorithms have been published in papers and can be found at https://hpi.de/naumann/publications/all-publications.html. The algorithm names aren't necessarily a part of the paper titles, though. If you can't find the paper for a specific algorithm, you can ask here.
